version: 2

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install
          command: pipenv install
      - run:
          name: Update Index
          command: cp README.md docs/index.md
      - run:
          name: Update Courses
          command: pipenv run python update.py
      - add_ssh_keys:
          fingerprints:
            - "10:c3:cd:c1:05:a1:c9:7e:23:05:bc:01:7d:ce:7f:b1"
      - run:
          name: Deploy docs to gh-pages branch
          command: pipenv run mkdocs gh-deploy